### ISSUE TITLE
Singularity and ezBIDS

### ISSUE THREAD

**Issue by andreifoldes** [brainlife/ezbids#100]
I've read about the Dev environment in the Readme and was wondering whether there was a way to launch it via `singularity`? 
I know that singularity can build docker recipes, but wanted to ask whether this would work "out of the box" for ezBIDS?

I would be awesome if people could use ezBIDS without having to upload the data to remote locations, but still be able to use the GUI...

**Comment by dlevitas** [comment]
Hi @andreifoldes, apologies for the delayed response.

> I've read about the Dev environment in the Readme and was wondering whether there was a way to launch it via `singularity`?
Currently, the ezBIDS dev instances can only be created with `docker`, but we're currently working on enabling `singularity` for this as well.


> I would be awesome if people could use ezBIDS without having to upload the data to remote locations, but still be able to use the GUI...

Agreed, other users have asked for this as well, so we're also working on this too. This will take a bit of time to disentangle the server-side communication, but once we have this up and running we'll let you know.

**Comment by dlevitas** [comment]
Hi @andreifoldes I apologize for not responding sooner.

Currently, users can install ezBIDS locally if they have access to both `Docker` and `docker-compose` (see the documentation [here](https://brainlife.io/docs/using_ezBIDS/#installing-ezbids-locally) for that). 

Since `Docker` isn't allowed on institution HPCs, I've looked into a `Singularity` and `singularity-compose` equivalent. Thus far, I haven't been able to make much headway on this front. The main issues are that `singularity-compose` isn't well supported and doesn't have a great one-to-one mapping with `docker-compose`. Furthermore, there still needs to be sudo/root access in order to get this to work, which defeats the purpose for HPC users since they lack these privileges. Lastly, ezBIDS wasn't designed to be installed and used locally (outside of `Docker`).

I've reached out to some software developer colleagues for second opinions on this. They agree that using `Singularity` and `singularity-compose` isn't likely to work, or will require an unreasonable amount of work to set up. This seems to fall outside the scope of the ezBIDS project, as it wasn't designed for this.

I'm therefore going to close this issue. If you or someone else are willing to tackle this, I'd be willing to collaborate, but for now I would recommend accessing ezBIDS via the web (default) or using the `Docker` installation. The [FAQ](https://brainlife.io/docs/using_ezBIDS/#faq) section provides clarification for users uneasy about data leaving their site.
