### ISSUE TITLE
[BUG] NIfTi's containing spaces? not picked up by ezBIDS

### ISSUE THREAD

**Issue by bendhouseart** [brainlife/ezbids#119]
Given an input directory like so:

```bash
[user@machine sub-02]$ tree -d
.
├── anat
└── ses-baseline
    └── sub-02_ses-baseline_trc-ps13_pet
```

Where `anat` contains the following nii file `'AG MRI 02.16.24.nii'` ezBIDS does not pick up on that MR image after upload:

<img width="761" alt="Screenshot 2024-02-16 at 1 41 30 PM" src="https://github.com/brainlife/ezbids/assets/28850131/8f63b19e-8a9c-4c62-9e7d-509e221581fc">

ezBIDS version is set to commit d5b2ff2831205b86cf85afd0994632950be2c77b

**Comment by bendhouseart** [comment]
Hmm might not be the spaces, renamed the file in question to `AG_MRI_02.16.24.nii` and same issue.

**Comment by dlevitas** [comment]
This appears to be an issue with how NIH anatomical data collected with PET acquisitions are transformed to NIfTI format outside of ezBIDS. The [unintended] result of this process is that the NIfTI files are now 4D with a singelton 4th dimension (see [here](https://neurostars.org/t/error-when-converting-t1w-to-bids-t1w-file-with-too-many-dimensions/2568/13) for related discussion). 

Can probably just add a `try except` block, but need to get a better sense of how to detect with improperly added 4th dimensions for otherwise 3D anatomical data.
