### ISSUE TITLE
excluded objects actually included in the download folder

### ISSUE THREAD

**Issue by giulia-berto** [brainlife/ezbids#47]
Hi, I noticed that the objects that I wanted to exclude from the BIDS conversion are actually included in the final folder that I downloaded. Actually, this happened in a specific case: I first uploaded some acquisitions, converted all of them to BIDS, and then download the final folder. Then, I realized that I wanted to exclude some objects, so I hit the "Back" button, excluded the identified objects, made the conversion again, and downloaded the folder. And here's where the issue happened. Probably if I had started the process from scratch, it would have worked?!

**Comment by dlevitas** [comment]
Hi @giulia-berto, this is by design. When one or more acquisitions are set to `exclude` ezBIDS generates an "excluded" folder and places all `exclude` acquisitions in there. The "excluded" folder is added to the `.bidsignore` to ensure that the BIDS-validator ignores it. 

The rationale for having this "excluded" folder is that users may wish to keep those acquisitions for analyses but the acquisitions aren't yet in the BIDS-specification. If however the "excluded" folder contains wholly unnecessary acquisitions (e.g. localizers, etc), you can simply delete the folder after downloading.

**Comment by giulia-berto** [comment]
I see, thanks. I restarted the process from scratch and actually obtained the same directory structure. I'll just have to delete the 'exclude' folder.

**Comment by soichih** [comment]
I guess we can add a check box during the finalize step so user can choose if they want to create `exclude` folder?

**Comment by giulia-berto** [comment]
I like the idea.

**Comment by soichih** [comment]
I've added a checkbox 
![image](https://user-images.githubusercontent.com/923896/157348133-522c497b-16b0-49da-9e93-8ff1467d4532.png)
