### ISSUE TITLE
BIDS ordering

### ISSUE THREAD

**Issue by andreifoldes** [brainlife/ezbids#58]
Greetings,

I experienced the following error at the bids validation stage:
```
bids-validator@1.9.2
bids-specification@disable
	1: [ERR] Files with such naming scheme are not part of BIDS specification. This error is most commonly caused by typos in file names that make them not BIDS compatible. Please consult the specification and make sure your files are named correctly. If this is not a file naming issue (for example when including files not yet covered by the BIDS specification) you should include a ".bidsignore" file in your dataset (see https://github.com/bids-standard/bids-validator#bidsignore for details). Please note that derived (processed) data should be placed in /derivatives folder and source data (such as DICOMS or behavioural logs in proprietary formats) should be placed in the /sourcedata folder. (code: 1 - NOT_INCLUDED)
		./sub-25052022/anat/acq-t2coronalRep_sub-25052022_T2star.json
			Evidence: acq-t2coronalRep_sub-25052022_T2star.json
		./sub-25052022/anat/acq-t2coronalRep_sub-25052022_T2star.nii.gz
		...
```
I believe that the ordering of the entities is off?

https://brainlife.io/ezbids/#629b646facfcf81054af5e44

**Comment by dlevitas** [comment]
Hi @andreifoldes ,

Thanks, this is a new issue we've encountered due to changes to the BIDS specification. The issue will be fixed on the main ezBIDS website early next week, but if you're under a time crunch, you can use the testing website (https://test.brainlife.io/ezbids/), where this issue has already been fixed. With the testing website though you can't push your BIDS data to brainlife.io

Once the changes are on the main website, which should be early next week, we'll let you know.

**Comment by dlevitas** [comment]
Hi @andreifoldes ,

This issue should now be fixed. Please re-open if it continues to persist.
